/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AuditActorType = "account" | "anonymous" | "staff" | "system";

export type AuditResult = "denied" | "failure" | "rate_limited" | "success";

export type AuditRetentionClass = "security" | "standard";

export type AuditRowOperation = "delete" | "insert" | "update";

export type AuthRole = "admin" | "moderator" | "partner";

export type ConfigLegalDocumentKind = "privacy" | "terms";

export type ConfigValueType = "bool" | "float" | "int" | "json" | "string" | "string_list";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MailCategory = "auth" | "notification" | "product" | "transactional";

export type MailMessageStatus = "bounced" | "cancelled" | "complained" | "delivered" | "delivery_delayed" | "failed" | "queued" | "sending" | "sent" | "suppressed";

export type MailSuppressionReason = "complaint" | "hard_bounce" | "manual";

export type ModerationBanSubject = "account" | "ip_range" | "vrchat_user";

export type ModerationReportReason = "harassment" | "hate" | "impersonation" | "malicious_link" | "minor_safety" | "other" | "sexual_content" | "spam";

export type ModerationReportStatus = "actioned" | "dismissed" | "in_review" | "open";

export type PagesDomainStatus = "active" | "disabled" | "failed" | "pending";

export type PagesInviteStatus = "accepted" | "declined" | "pending" | "revoked";

export type PagesPageKind = "group" | "user";

export type PagesRefreshTier = "cold" | "dormant" | "hot" | "warm";

export type PagesSlugRole = "alias" | "primary";

export type PagesTlsStatus = "active" | "failed" | "pending";

export type PagesVisibility = "private" | "public" | "unlisted";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type VrchatCallOutcome = "auth_failed" | "network_error" | "not_found" | "ok" | "rate_limited" | "server_error" | "timeout";

export type VrchatClaimStatus = "cancelled" | "denied" | "exhausted" | "expired" | "pending" | "succeeded";

export type VrchatEndpoint = "get_group" | "get_user" | "get_user_status";

export type VrchatFetchError = "not_found" | "rate_limited" | "unavailable";

export type VrchatGroupPrivacy = "default" | "private";

export type VrchatJobKind = "claim_check" | "group_refresh" | "user_refresh";

export type VrchatJobStatus = "cancelled" | "failed" | "queued" | "running" | "succeeded";

export type VrchatLane = "headroom" | "manual" | "scheduled" | "verification";

export type VrchatTargetKind = "group" | "user";

export type VrchatUserStatus = "active" | "ask_me" | "busy" | "join_me" | "offline";

export interface AuditEvents {
  action: string;
  actorAccountId: string | null;
  actorType: AuditActorType;
  id: Generated<string>;
  /**
   * IP of whoever acted, on every event, for the admin logs. Security events are kept longer (retention).
   */
  ip: string | null;
  ipCountry: string | null;
  /**
   * Action-specific detail. Never holds a secret.
   */
  metadata: Generated<Json>;
  occurredAt: Generated<Timestamp>;
  requestId: string | null;
  result: Generated<AuditResult>;
  /**
   * standard: kept log.retention.audit_days. security: kept log.retention.security_days.
   */
  retention: Generated<AuditRetentionClass>;
  sessionId: string | null;
  targetId: string | null;
  targetType: string | null;
  /**
   * Browser of whoever acted, on every event.
   */
  userAgent: string | null;
}

export interface AuditRowChanges {
  actorAccountId: string | null;
  /**
   * From app.actor_type. NULL when the write carried no app context (Better Auth, manual psql).
   */
  actorType: AuditActorType | null;
  changedAt: Generated<Timestamp>;
  /**
   * session_user: the login that made the change, even through cascades.
   */
  dbRole: string;
  id: Generated<string>;
  newValues: Json | null;
  /**
   * Update: only the changed columns. Delete: the whole row, minus ignored columns.
   */
  oldValues: Json | null;
  operation: AuditRowOperation;
  requestId: string | null;
  rowKey: Json;
  schemaName: string;
  tableName: string;
  txId: Int8;
}

export interface AuthAccountPreferences {
  accountId: string;
  createdAt: Generated<Timestamp>;
  dyslexiaFont: Generated<boolean>;
  highContrast: Generated<boolean>;
  /**
   * Light colours instead of dark (light mode on the website).
   */
  lightMode: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  /**
   * Updates published after this are new to the account. NULL: its creation time.
   */
  updatesSeenAt: Timestamp | null;
}

export interface AuthAccountRoles {
  accountId: string;
  grantedAt: Generated<Timestamp>;
  grantedBy: string | null;
  note: string | null;
  role: AuthRole;
}

export interface AuthAccounts {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  image: string | null;
  isEmailVerified: Generated<boolean>;
  /**
   * Can be empty: an email sign-up has no name.
   */
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface AuthIdentities {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerAccountId: string;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface AuthNotificationPreferences {
  accountId: string;
  createdAt: Generated<Timestamp>;
  notifyGroupInvites: Generated<boolean>;
  notifyPageChanges: Generated<boolean>;
  notifyProductNews: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
}

export interface AuthRateLimits {
  count: number;
  id: Generated<string>;
  key: string;
  /**
   * Unix time in milliseconds, as Better Auth writes it.
   */
  lastRequest: Int8;
}

export interface AuthSessions {
  accountId: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  /**
   * Text, not inet: Better Auth may write an empty string.
   */
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
}

export interface AuthVerifications {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface ConfigLegalAcceptances {
  acceptedAt: Generated<Timestamp>;
  accountId: string;
  documentId: string;
  id: Generated<string>;
  sessionId: string | null;
}

export interface ConfigLegalDocuments {
  contentSha256: Buffer;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  kind: ConfigLegalDocumentKind;
  publishedAt: Timestamp;
  url: string;
  version: string;
}

export interface ConfigSettings {
  category: string;
  createdAt: Generated<Timestamp>;
  description: string;
  key: string;
  maxValue: Json | null;
  minValue: Json | null;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
  value: Json;
  valueType: ConfigValueType;
}

export interface MailEvents {
  id: Generated<string>;
  messageId: string | null;
  occurredAt: Timestamp;
  payload: Json;
  receivedAt: Generated<Timestamp>;
  resendEmailId: string | null;
  type: string;
  /**
   * The svix-id header, so a webhook delivered twice is stored once.
   */
  webhookId: string;
}

export interface MailMessages {
  accountId: string | null;
  attempts: Generated<number>;
  bouncedAt: Timestamp | null;
  category: MailCategory;
  complainedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  deliveredAt: Timestamp | null;
  id: Generated<string>;
  idempotencyKey: string | null;
  lastError: string | null;
  /**
   * The data the template was rendered with. Never a secret.
   */
  props: Generated<Json>;
  resendEmailId: string | null;
  scheduledFor: Generated<Timestamp>;
  sentAt: Timestamp | null;
  status: Generated<MailMessageStatus>;
  subject: string;
  template: string;
  toEmail: string;
  updatedAt: Generated<Timestamp>;
}

export interface MailSuppressions {
  createdAt: Generated<Timestamp>;
  email: string;
  reason: MailSuppressionReason;
  sourceEventId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface ModerationActiveBans {
  accountId: string | null;
  createdAt: Timestamp | null;
  createdBy: string | null;
  expiresAt: Timestamp | null;
  id: string | null;
  ipRange: string | null;
  liftedAt: Timestamp | null;
  liftedBy: string | null;
  liftReason: string | null;
  publicReason: string | null;
  reason: string | null;
  subjectType: ModerationBanSubject | null;
  updatedAt: Timestamp | null;
  vrchatUserId: string | null;
}

export interface ModerationBanEvidence {
  addedAt: Generated<Timestamp>;
  addedBy: string | null;
  auditEventId: string | null;
  banId: string;
  eventSnapshot: Json;
  id: Generated<string>;
  note: string | null;
}

export interface ModerationBans {
  /**
   * No foreign key: a ban outlives the account it was placed on.
   */
  accountId: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  /**
   * NULL means permanent.
   */
  expiresAt: Timestamp | null;
  id: Generated<string>;
  ipRange: string | null;
  liftedAt: Timestamp | null;
  liftedBy: string | null;
  liftReason: string | null;
  publicReason: string;
  /**
   * Internal. public_reason is what the banned person sees.
   */
  reason: string;
  subjectType: ModerationBanSubject;
  updatedAt: Generated<Timestamp>;
  vrchatUserId: string | null;
}

export interface ModerationReports {
  assignedTo: string | null;
  banId: string | null;
  createdAt: Generated<Timestamp>;
  details: string | null;
  id: Generated<string>;
  pageId: string | null;
  reason: ModerationReportReason;
  reporterAccountId: string | null;
  /**
   * Same hash as pages.views.visitor_hash; set for every reporter, signed in or not, and used for the daily cap.
   */
  reporterVisitorHash: Buffer;
  resolutionNote: string | null;
  resolvedAt: Timestamp | null;
  resolvedBy: string | null;
  status: Generated<ModerationReportStatus>;
  targetSnapshot: Json;
  updatedAt: Generated<Timestamp>;
}

export interface NewsMedia {
  bytes: Buffer;
  byteSize: number;
  contentType: string;
  createdAt: Generated<Timestamp>;
  height: number | null;
  id: Generated<string>;
  sha256: Buffer;
  width: number | null;
}

export interface NewsUpdates {
  body: string;
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  id: Generated<string>;
  mediaId: string | null;
  publishedAt: Timestamp | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface PagesCustomDomains {
  createdAt: Generated<Timestamp>;
  hostname: string;
  id: Generated<string>;
  lastCheckedAt: Timestamp | null;
  lastError: string | null;
  pageId: string;
  providerHostnameId: string | null;
  status: Generated<PagesDomainStatus>;
  tlsStatus: Generated<PagesTlsStatus>;
  updatedAt: Generated<Timestamp>;
  verificationToken: string;
  verifiedAt: Timestamp | null;
}

export interface PagesEditorInvites {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  invitedAccountId: string;
  invitedByAccountId: string;
  pageId: string;
  respondedAt: Timestamp | null;
  status: Generated<PagesInviteStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface PagesEditors {
  accountId: string;
  addedAt: Generated<Timestamp>;
  pageId: string;
}

export interface PagesHiddenLinks {
  createdAt: Generated<Timestamp>;
  identity: string;
  pageId: string;
}

export interface PagesLinks {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * Marked 18+ by the page's owner or an editor. Visitors confirm before it opens.
   */
  isAdult: Generated<boolean>;
  /**
   * Kept on the page's list but not shown to visitors.
   */
  isHidden: Generated<boolean>;
  label: string | null;
  pageId: string;
  position: number;
  updatedAt: Generated<Timestamp>;
  /**
   * Normalized https URL.
   */
  url: string;
}

export interface PagesPageOverview {
  createdAt: Timestamp | null;
  displayName: string | null;
  isHidden: boolean | null;
  kind: PagesPageKind | null;
  lastViewedAt: Timestamp | null;
  ownerAccountId: string | null;
  ownerEmail: string | null;
  pageId: string | null;
  primarySlug: string | null;
  refreshTier: PagesRefreshTier | null;
  visibility: PagesVisibility | null;
  vrchatId: string | null;
}

export interface PagesPages {
  /**
   * The page's accent colour, #rrggbb. NULL: vrc.page's own.
   */
  accent: string | null;
  /**
   * A banner uploaded on vrc.page, shown instead of the VRChat banner.
   */
  bannerImageId: string | null;
  createdAt: Generated<Timestamp>;
  /**
   * Moderator takedown. The owner cannot undo it.
   */
  hiddenAt: Timestamp | null;
  hiddenBy: string | null;
  hiddenReason: string | null;
  id: Generated<string>;
  /**
   * Picked by an admin as the home page example. Shown only while the page is a public, visible user page.
   */
  isShowcase: Generated<boolean>;
  kind: PagesPageKind;
  lastViewedAt: Timestamp | null;
  nextRefreshAt: Generated<Timestamp>;
  /**
   * A picture uploaded on vrc.page, shown instead of the VRChat icon.
   */
  pictureImageId: string | null;
  refreshTier: Generated<PagesRefreshTier>;
  /**
   * When the primary name last changed; the rename cooldown counts from here.
   */
  slugChangedAt: Timestamp | null;
  /**
   * False: no Socials page; vrc.page/<name>/socials goes to the profile.
   */
  socialsEnabled: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<PagesVisibility>;
  vrchatGroupId: string | null;
  vrchatUserId: string | null;
}

export interface PagesSlugs {
  blockedUntil: Timestamp | null;
  claimedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  /**
   * Aliases only: true sends a 308 to the primary, false serves the page at this name.
   */
  isRedirect: Generated<boolean>;
  /**
   * NULL while the name is held after release. Reclaiming an expired hold updates this row.
   */
  pageId: string | null;
  releasedAt: Timestamp | null;
  /**
   * primary: the page's address. alias: another name for it, which redirects (308) to the primary unless is_redirect is false.
   */
  role: PagesSlugRole;
  /**
   * The name, lowercase. The same as slug_key.
   */
  slug: string;
  slugKey: string;
  updatedAt: Generated<Timestamp>;
}

export interface PagesViewDaily {
  day: Timestamp;
  pageId: string;
  uniqueVisitors: number;
  views: number;
}

export interface PagesViews {
  country: string | null;
  occurredAt: Generated<Timestamp>;
  pageId: string;
  referrerHost: string | null;
  /**
   * Random id the browser made for this visit; ties the view to its rows in pages.visit_events.
   */
  visitId: string | null;
  /**
   * HMAC of the IP with a monthly key derived from a secret the API holds. Counts uniques; cannot be reversed here.
   */
  visitorHash: Buffer;
}

export interface PagesVisitEvents {
  kind: string;
  /**
   * For a click: the page's own copy of the link opened, never what the browser sent.
   */
  linkUrl: string | null;
  occurredAt: Generated<Timestamp>;
  pageId: string;
  /**
   * For a leave: seconds the page was visible, capped at 30 minutes.
   */
  seconds: number | null;
  visitId: string;
}

export interface VrchatApiCalls {
  durationMs: number;
  endpoint: VrchatEndpoint;
  error: string | null;
  /**
   * NULL when no response arrived (network error or timeout).
   */
  httpStatus: number | null;
  id: Generated<string>;
  jobId: string | null;
  lane: VrchatLane;
  outcome: VrchatCallOutcome;
  retryAfterSeconds: number | null;
  startedAt: Timestamp;
  targetId: string;
}

export interface VrchatBudgetToday {
  callsAllowed: number | null;
  callsUsed: number | null;
  lane: VrchatLane | null;
}

export interface VrchatClaimCodes {
  accountId: string;
  checkCount: Generated<number>;
  code: string;
  createdAt: Generated<Timestamp>;
  /**
   * Why a matching code was still refused, e.g. already_connected, not_group_owner, group_private, banned.
   */
  deniedReason: string | null;
  /**
   * The VRChat display name or group name, as it read when the code was issued. Saves a call when the claim is reopened.
   */
  displayName: string | null;
  expiresAt: Timestamp;
  id: Generated<string>;
  lastCheckedAt: Timestamp | null;
  resolvedAt: Timestamp | null;
  status: Generated<VrchatClaimStatus>;
  targetKind: VrchatTargetKind;
  updatedAt: Generated<Timestamp>;
  vrchatGroupId: string | null;
  vrchatUserId: string | null;
}

export interface VrchatClientState {
  /**
   * The value of VRChat's auth cookie for the service account. NULL means the next read signs in first.
   */
  authCookie: string | null;
  backoffSeconds: Generated<number>;
  backoffUntil: Timestamp | null;
  circuitOpenedAt: Timestamp | null;
  circuitReason: string | null;
  consecutiveAuthFailures: Generated<number>;
  id: Generated<boolean>;
  nextCallAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface VrchatGroups {
  bannerImageId: string | null;
  claimedAt: Generated<Timestamp>;
  claimedByVrchatUserId: string;
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  discriminator: string;
  fetchedAt: Timestamp;
  iconImageId: string | null;
  id: string;
  isVerified: Generated<boolean>;
  languages: Generated<string[]>;
  lastFetchError: VrchatFetchError | null;
  lastFetchErrorAt: Timestamp | null;
  links: Generated<string[]>;
  memberCount: Generated<number>;
  name: string;
  /**
   * The owner as VRChat reports it. The API unclaims the group when this stops matching the claimer.
   */
  ownerVrchatUserId: string;
  privacy: VrchatGroupPrivacy;
  rules: string | null;
  shortCode: string;
  updatedAt: Generated<Timestamp>;
}

export interface VrchatImages {
  bytes: Buffer;
  byteSize: number;
  createdAt: Generated<Timestamp>;
  height: number;
  id: Generated<string>;
  sha256: Buffer;
  /**
   * The address VRChat gave for this picture most recently. A refresh that sees it again downloads nothing. NULL for a picture or banner uploaded on vrc.page.
   */
  sourceUrl: string | null;
  width: number;
}

export interface VrchatJobs {
  attempts: Generated<number>;
  claimCodeId: string | null;
  createdAt: Generated<Timestamp>;
  error: string | null;
  finishedAt: Timestamp | null;
  id: Generated<string>;
  kind: VrchatJobKind;
  lane: VrchatLane;
  pageId: string | null;
  /**
   * Lower runs first.
   */
  priority: Generated<number>;
  /**
   * The account that pressed refresh or check. Also answers the manual daily cap.
   */
  requestedBy: string | null;
  runAfter: Generated<Timestamp>;
  startedAt: Timestamp | null;
  status: Generated<VrchatJobStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface VrchatUsers {
  accountId: string;
  bannerImageId: string | null;
  bio: Generated<string>;
  bioLinks: Generated<string[]>;
  /**
   * When the bio code matched: the GDPR consent record, with the link.succeeded audit event.
   */
  connectedAt: Generated<Timestamp>;
  createdAt: Generated<Timestamp>;
  displayName: string;
  /**
   * Last successful read from VRChat.
   */
  fetchedAt: Timestamp;
  iconImageId: string | null;
  id: string;
  isAgeVerified: Generated<boolean>;
  languages: Generated<string[]>;
  lastFetchError: VrchatFetchError | null;
  lastFetchErrorAt: Timestamp | null;
  pronouns: string | null;
  representedGroupId: string | null;
  representedGroupName: string | null;
  status: Generated<VrchatUserStatus>;
  statusDescription: string | null;
  trustRank: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  "audit.events": AuditEvents;
  "audit.rowChanges": AuditRowChanges;
  "auth.accountPreferences": AuthAccountPreferences;
  "auth.accountRoles": AuthAccountRoles;
  "auth.accounts": AuthAccounts;
  "auth.identities": AuthIdentities;
  "auth.notificationPreferences": AuthNotificationPreferences;
  "auth.rateLimits": AuthRateLimits;
  "auth.sessions": AuthSessions;
  "auth.verifications": AuthVerifications;
  "config.legalAcceptances": ConfigLegalAcceptances;
  "config.legalDocuments": ConfigLegalDocuments;
  "config.settings": ConfigSettings;
  "mail.events": MailEvents;
  "mail.messages": MailMessages;
  "mail.suppressions": MailSuppressions;
  "moderation.activeBans": ModerationActiveBans;
  "moderation.banEvidence": ModerationBanEvidence;
  "moderation.bans": ModerationBans;
  "moderation.reports": ModerationReports;
  "news.media": NewsMedia;
  "news.updates": NewsUpdates;
  "pages.customDomains": PagesCustomDomains;
  "pages.editorInvites": PagesEditorInvites;
  "pages.editors": PagesEditors;
  "pages.hiddenLinks": PagesHiddenLinks;
  "pages.links": PagesLinks;
  "pages.pageOverview": PagesPageOverview;
  "pages.pages": PagesPages;
  "pages.slugs": PagesSlugs;
  "pages.viewDaily": PagesViewDaily;
  "pages.views": PagesViews;
  "pages.visitEvents": PagesVisitEvents;
  "vrchat.apiCalls": VrchatApiCalls;
  "vrchat.budgetToday": VrchatBudgetToday;
  "vrchat.claimCodes": VrchatClaimCodes;
  "vrchat.clientState": VrchatClientState;
  "vrchat.groups": VrchatGroups;
  "vrchat.images": VrchatImages;
  "vrchat.jobs": VrchatJobs;
  "vrchat.users": VrchatUsers;
}
